default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: flatiron_mod3_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: flatiron_mod3_test
  username: postgres
  password: password

production:
  <<: *default
  database: flatiron_mod3_production
